Vagrant.configure("2") do |config|
  config.vm.box = "neslog/CentOS-BroSysmon"
  config.vm.box_version = "0.1"
  config.vm.network "public_network", :type => 'dhcp', :adapter => 1
  config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
  config.vm.network "private_network", :type => 'dhcp', :adapter => 3
end
