Vagrant.configure("2") do |config|
  config.vm.box = "neslog/Windows-BroSysmon"
  config.vm.network "private_network", ip: "192.168.100.100", virtualbox__intnet: true, adapter: 1
  config.vm.network "private_network", type: "dhcp", adapter: 2
end

